wiki2018.tr:
  is_metadata_in_cache_size: 0
  cache_sizes:
#    - 68719476736
#    - 137438953472
#    - 274877906944
#    - 549755813888
#    - 1099511627776
    - 68719476736:
        LRU:
          max_n_element:
#            - 262144
#            - 16384
            - 59049 # fit
#        LRB:
#          memory_window:
#            - 58720256
#          byte_million_req:
#            - 35234263115
    - 137438953472:
        LRU:
          max_n_element:
#            - 524288
#            - 16384
            - 131072 # fit
#        LRB:
#          memory_window:
#            - 100663296
#          byte_million_req:
#            - 35234263115
    - 274877906944:
        LRU:
          max_n_element:
#            - 1594323
#            - 65536
            - 524288 # fit
#        LRB:
#          memory_window:
#            - 167772160
#          byte_million_req:
#            - 35234263115
#    - 549755813888:
#        LRU:
#          max_n_element:
##            - 1048576
##            - 262144
#        LRB:
#          memory_window:
#            - 335544320
#          byte_million_req:
#            - 35234263115
    - 1099511627776:
        LRU:
          max_n_element:
##            - 4194304
##            - 1000000
            - 2097152 # fit
#        LRB:
#          memory_window:
#            - 671088640
#          byte_million_req:
#            - 35234263115
  n_req: 2800000000
  n_early_stop:
    - -1
  segment_window: 10000000
  real_time_segment_window: 6000
  enable_trace_format_check: 0
#  max_n_element:
##    - 10000000 # nuggets
##    - 5000000
#    - 15000000 # nhit
#    - 30000000
##        - 1
##        - 2
##        - 4
##        - 8
##        - 16
##        - 32
##        - 64
##        - 128
##        - 256
##        - 512
##        - 1024
##        - 2048
##        - 4096
##        - 8192
#    - 16384
#    - 32768
#    - 65536
#    - 131072
#    - 262144
#    - 524288
#    - 1048576
#    - 2097152
#    - 4194304
#    - 8388608
#    - 16777216
#    - 33554432
#    - 67108864
#    - 134217728
#    - 268435456
#    - 536870912
#    - 1073741824
##        - 3
##        - 9
##        - 27
##        - 81
##        - 243
##        - 729
##        - 2187
##        - 6561
#    - 19683
#    - 59049
#    - 177147
#    - 531441
#    - 1594323
#    - 4782969
#    - 14348907
#    - 43046721
#    - 129140163
#    - 387420489
#    - 1162261467
##        - 10
##        - 100
##        - 1000
#    - 10000
#    - 100000
#    - 1000000
#    - 10000000
#    - 100000000
#    - 40000000
  bloom_k:
    - 2
##    - 4
##    - 8
##    - 16
##    - 32
##  bloom_track_k_hit: 1
  version:
    - 2
  filter_type:
#    #    - Set
#    - IntervalBloom
    - Bloom
#  refresh_interval:
#    - 172800 # nuggets
#    - 463856 # n-hit
#  access_resource_counter_window: 100000
#  access_resource_counter_reduction_factor: 100000
#  track_access_frequency_hit: 1
#  track_access_resource_hit: 1
#  track_access_age_hit: 1
#  track_eviction_age: 1
#  bloom_record_reset: 1
#  track_no_hit_eviction_age: 1
  track_admission: 1
#  bloom_track_fp: 1
#  track_interrequest_classification: 1
#  stop_seq: 1400000000

wiki2019.tr:
#  is_metadata_in_cache_size: 0
  cache_sizes:
#  - 68719476736
#  - 137438953472
#  - 274877906944
  - 549755813888
#  - 1099511627776
#    - 68719476736:
#        LRU:
#          max_n_element:
#            - 400000
#            - 177147
#        LRB:
#          memory_window:
#            - 58720256
#          byte_million_req:
#            - 35234263115
#    - 137438953472:
#        LRU:
#          max_n_element:
#            - 600000 # heuristic
##            - 400000
##            - 177147
#        LRB:
#          memory_window:
#            - 100663296
#          byte_million_req:
#            - 35234263115
#    - 274877906944:
#        LRU:
#          max_n_element:
#            - 1000000
##            - 400000
##            - 177147
#        LRB:
#          memory_window:
#            - 167772160
#          byte_million_req:
#            - 35234263115
#    - 549755813888:
#        LRU:
#          max_n_element:
#            - 524288 # opt
#            - 2097152 # heuristic
##            - 400000
##            - 177147
#        LRB:
#          memory_window:
#            - 335544320
#          byte_million_req:
#            - 35234263115
#    - 1099511627776:
#        LRU:
#          max_n_element:
##            - 400000
##            - 177147
#            - 4194304 # opt
#            - 4782969 # heuristic
#        LRB:
#          memory_window:
#            - 671088640
#          byte_million_req:
#            - 35234263115
  n_req: 2800000000
  n_early_stop:
    - -1
  segment_window: 10000000
  real_time_segment_window: 6000
  enable_trace_format_check: 0
  max_n_element:
#    - 10000000 # nuggets
#    - 5000000
#    - 21000000 # nhit
#    - 42000000
#    - 1
#    - 2
#    - 4
#    - 8
#    - 16
#    - 32
#    - 64
#    - 128
#    - 256
#    - 512
#    - 1024
#    - 2048
#    - 4096
#    - 8192
    - 16384
    - 32768
    - 65536
    - 131072
    - 262144
    - 524288
    - 1048576
    - 2097152
    - 4194304
    - 8388608
    - 16777216
    - 33554432
    - 67108864
    - 134217728
    - 268435456
    - 536870912
#    - 1073741824
#    - 3
#    - 9
#    - 27
#    - 81
#    - 243
#    - 729
#    - 2187
#    - 6561
    - 19683
    - 59049
    - 177147
    - 531441
    - 1594323
    - 4782969
    - 14348907
    - 43046721
    - 129140163
#    - 387420489
#    - 1162261467
#    - 10
#    - 100
#    - 1000
    - 10000
    - 100000
    - 1000000
    - 10000000
    - 100000000
    - 40000000
  bloom_k:
#    - 1
    - 2
#    - 4
#    - 8
#    - 16
#    - 32
#  bloom_track_k_hit: 1
  version:
    - 2
  filter_type:
    - Bloom
#    - IntervalBloom
#  refresh_interval:
#    - 172800 # nuggets
#    - 733507 # nhit
#  access_resource_counter_window: 100000
#  access_resource_counter_reduction_factor: 100000
#  track_access_frequency_hit: 1
#  track_access_resource_hit: 1
#  track_access_age_hit: 1
#  track_eviction_age: 1
#  track_no_hit_eviction_age: 1
#  bloom_record_reset: 1
#  track_admission: 1
#  bloom_track_fp: 1
#  track_interrequest_classification: 1
#  stop_seq: 1328000000

